In [102]:
import pandas as pd

df = pd.read_csv('global_data.csv')

In [103]:
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [104]:
# Mevcut sütun isimlerini yeni isimlerle değiştirme
df.columns = [
    "Ulke",  # Entity
    "Yil",  # Year
    "Elektrik_Erisim_%",  # Access to electricity (% of population)
    "Temiz_Yakit_Erisim",  # Access to clean fuels for cooking
    "Yenilenebilir_Kapasite_KisiBasi",  # Renewable-electricity-generating-capacity-per-capita
    "Gelismis_Ulkeler_Finansal_Akisi",  # Financial flows to developing countries (US $)
    "Yenilenebilir_Enerji_Orani",  # Renewable energy share in the total final energy consumption (%)
    "Fosil_Yakit_Elektrik_TWh",  # Electricity from fossil fuels (TWh)
    "Nukleer_Elektrik_TWh",  # Electricity from nuclear (TWh)
    "Yenilenebilir_Elektrik_TWh",  # Electricity from renewables (TWh)
    "Dusuk_Karbon_Elektrik_%",  # Low-carbon electricity (% electricity)
    "KisiBasi_Enerji_Tuketimi",  # Primary energy consumption per capita (kWh/person)
    "Enerji_Yoğunluğu",  # Energy intensity level of primary energy (MJ/$2017 PPP GDP)
    "CO2_Emisyonu_kt",  # Value_co2_emissions_kt_by_country
    "Yenilenebilir_Enerji_%",  # Renewables (% equivalent primary energy)
    "Gdp_Buyume",  # gdp_growth
    "Gdp_KisiBasi",  # gdp_per_capita
    "Nufus_Yogunlugu",  # Density\n(P/Km2)
    "Yuzolcumu_Km2",  # Land Area(Km2)
    "Enlem",  # Latitude
    "Boylam"  # Longitude
]

# Yeni sütun isimlerini kontrol edelim
df

,Ulke,Yil,Elektrik_Erisim_%,Temiz_Yakit_Erisim,Yenilenebilir_Kapasite_KisiBasi,Gelismis_Ulkeler_Finansal_Akisi,Yenilenebilir_Enerji_Orani,Fosil_Yakit_Elektrik_TWh,Nukleer_Elektrik_TWh,Yenilenebilir_Elektrik_TWh,...,KisiBasi_Enerji_Tuketimi,Enerji_Yoğunluğu,CO2_Emisyonu_kt,Yenilenebilir_Enerji_%,Gdp_Buyume,Gdp_KisiBasi,Nufus_Yogunlugu,Yuzolcumu_Km2,Enlem,Boylam
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [105]:
missing_data = df.isnull().sum()
print("Eksik veri sayısı:", missing_data[missing_data > 0])

Eksik veri sayısı: Elektrik_Erisim_%                    10
Temiz_Yakit_Erisim                  169
Yenilenebilir_Kapasite_KisiBasi     931
Gelismis_Ulkeler_Finansal_Akisi    2089
Yenilenebilir_Enerji_Orani          194
Fosil_Yakit_Elektrik_TWh             21
Nukleer_Elektrik_TWh                126
Yenilenebilir_Elektrik_TWh           21
Dusuk_Karbon_Elektrik_%              42
Enerji_Yoğunluğu                    207
CO2_Emisyonu_kt                     428
Yenilenebilir_Enerji_%             2137
Gdp_Buyume                          317
Gdp_KisiBasi                        282
Nufus_Yogunlugu                       1
Yuzolcumu_Km2                         1
Enlem                                 1
Boylam                                1
dtype: int64

In [106]:
# 'Nufus_Yogunlugu' sütununu float64 türüne çevirelim
df['Nufus_Yogunlugu'] = pd.to_numeric(df['Nufus_Yogunlugu'], errors='coerce')

In [107]:
# Sadece sayısal sütunların seçilmesi
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns

# Sadece sayısal sütunlardaki eksik değerleri sütunun ortalaması ile doldurulması
df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].mean())

df.head(10)

,Ulke,Yil,Elektrik_Erisim_%,Temiz_Yakit_Erisim,Yenilenebilir_Kapasite_KisiBasi,Gelismis_Ulkeler_Finansal_Akisi,Yenilenebilir_Enerji_Orani,Fosil_Yakit_Elektrik_TWh,Nukleer_Elektrik_TWh,Yenilenebilir_Elektrik_TWh,...,KisiBasi_Enerji_Tuketimi,Enerji_Yoğunluğu,CO2_Emisyonu_kt,Yenilenebilir_Enerji_%,Gdp_Buyume,Gdp_KisiBasi,Nufus_Yogunlugu,Yuzolcumu_Km2,Enlem,Boylam
0,Afghanistan,2000,1.613591,6.20,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,11.986707,3.441610,13283.774348,60.0,652230.0,33.93911,67.709953
1,Afghanistan,2001,4.074574,7.20,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,11.986707,3.441610,13283.774348,60.0,652230.0,33.93911,67.709953
2,Afghanistan,2002,9.409158,8.20,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,11.986707,3.441610,179.426579,60.0,652230.0,33.93911,67.709953
3,Afghanistan,2003,14.738506,9.50,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,11.986707,8.832278,190.683814,60.0,652230.0,33.93911,67.709953
4,Afghanistan,2004,20.064968,10.90,7.75,94224000.0,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,11.986707,1.414118,211.382074,60.0,652230.0,33.93911,67.709953
5,Afghanistan,2005,25.390894,12.20,7.51,9830000.0,33.88,0.34,0.0,0.59,...,252.06912,1.41,1549.999952,11.986707,11.229715,242.031313,60.0,652230.0,33.93911,67.709953
6,Afghanistan,2006,30.718690,13.85,7.40,10620000.0,31.89,0.20,0.0,0.64,...,304.42090,1.50,1759.999990,11.986707,5.357403,263.733602,60.0,652230.0,33.93911,67.709953
7,Afghanistan,2007,36.051010,15.30,7.25,15750000.0,28.78,0.20,0.0,0.75,...,354.27990,1.53,1769.999981,11.986707,13.826320,359.693158,60.0,652230.0,33.93911,67.709953
8,Afghanistan,2008,42.400000,16.70,7.49,16170000.0,21.17,0.19,0.0,0.54,...,607.83350,1.94,3559.999943,11.986707,3.924984,364.663542,60.0,652230.0,33.93911,67.709953
9,Afghanistan,2009,46.740050,18.40,7.50,9960000.0,16.53,0.16,0.0,0.78,...,975.04816,2.25,4880.000114,11.986707,21.390528,437.268740,60.0,652230.0,33.93911,67.709953

In [108]:
# 2020 yılına ait satırları çıkartma
df = df[df['Yil'] != 2020]

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3474 entries, 0 to 3647
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Ulke                             3474 non-null   object
 1   Yil                              3474 non-null   int64
 2   Elektrik_Erisim_%                3474 non-null   float64
 3   Temiz_Yakit_Erisim               3474 non-null   float64
 4   Yenilenebilir_Kapasite_KisiBasi  3474 non-null   float64
 5   Gelismis_Ulkeler_Finansal_Akisi  3474 non-null   float64
 6   Yenilenebilir_Enerji_Orani       3474 non-null   float64
 7   Fosil_Yakit_Elektrik_TWh         3474 non-null   float64
 8   Nukleer_Elektrik_TWh             3474 non-null   float64
 9   Yenilenebilir_Elektrik_TWh       3474 non-null   float64
 10  Dusuk_Karbon_Elektrik_%          3474 non-null   float64
 11  KisiBasi_Enerji_Tuketimi         3474 non-null   float64
 12  Enerji_Yoğunluğu                 3474 non-null   float64
 13  CO2_Emisyonu_kt                  3474 non-null   float64
 14  Yenilenebilir_Enerji_%           3474 non-null   float64
 15  Gdp_Buyume                       3474 non-null   float64
 16  Gdp_KisiBasi                     3474 non-null   float64
 17  Nufus_Yogunlugu                  3474 non-null   float64
 18  Yuzolcumu_Km2                    3474 non-null   float64
 19  Enlem                            3474 non-null   float64
 20  Boylam                           3474 non-null   float64
dtypes: float64(19), int64(1), object(1)
memory usage: 597.1+ KB

In [111]:
df = df.copy()

df['Kalkinma_Endeksi'] = (-1 * (
    0.15 * df['Elektrik_Erisim_%'] +
    0.15 * df['Temiz_Yakit_Erisim'] +
    0.1 * df['Yenilenebilir_Kapasite_KisiBasi'] +
    0.1 * df['Yenilenebilir_Enerji_Orani'] +
    0.2 * df['Gdp_KisiBasi'] +
    0.15 * df['Gdp_Buyume'] -
    0.1 * df['Fosil_Yakit_Elektrik_TWh'] -
    0.05 * df['CO2_Emisyonu_kt']
    ))

In [112]:
# Ülkelerin kalkınma endeksi ortalamalarını hesaplama
country_avg_index = df.groupby('Ulke')['Kalkinma_Endeksi'].mean().reset_index()

# Yeni veri seti: Sadece ülke adları ve ortalama kalkınma indeksleri
country_avg_index = country_avg_index.sort_values(by='Kalkinma_Endeksi', ascending=False)

In [113]:
country_avg_index.tail(60)

                    Ulke  Kalkinma_Endeksi
20                Bhutan       -575.058102
164               Tuvalu       -579.445967
53              Eswatini       -658.406232
136                Samoa       -665.755829
124             Paraguay       -671.301842
159                Tonga       -702.025152
69                Guyana       -706.625244
109              Namibia       -733.170076
55                  Fiji       -819.724129
120                 Oman       -856.742405
17                Belize       -876.718128
22              Botswana       -954.615595
112          Netherlands      -1095.445061
51               Eritrea      -1097.118980
153             Suriname      -1169.983929
59                 Gabon      -1255.726622
128             Portugal      -1265.992704
98              Maldives      -1271.524619
45              Dominica      -1318.300641
38            Costa Rica      -1328.421956
105           Montenegro      -1374.662163
102            Mauritius      -1400.840450
122               Panama      -1429.784514
39               Croatia      -1495.538388
65               Grenada      -1521.051038
149          South Sudan      -1560.944710
147              Somalia      -1738.351314
93             Lithuania      -1827.470861
88                Latvia      -1981.397810
170              Uruguay      -2025.586031
160  Trinidad and Tobago      -2094.108052
50     Equatorial Guinea      -2107.795543
52               Estonia      -2156.775712
110                Nauru      -2274.203274
141           Seychelles      -2419.243795
4    Antigua and Barbuda      -2712.772823
78                Israel      -2749.695320
12               Bahrain      -2827.090687
16               Belgium      -2898.891695
14              Barbados      -3005.775211
86                Kuwait      -3268.424388
145             Slovenia      -3443.429314
7                  Aruba      -3617.609219
100                Malta      -4079.336882
41                Cyprus      -4869.806168
114          New Zealand      -4882.886233
113        New Caledonia      -4987.162408
9                Austria      -5220.780222
56               Finland      -5828.466320
143            Singapore      -6695.477339
154               Sweden      -7485.434609
43               Denmark      -8306.715723
77               Ireland      -8658.496131
130                Qatar      -8953.020803
73               Iceland     -10285.893426
30        Cayman Islands     -10718.147622
155          Switzerland     -12007.921679
119               Norway     -13155.105909
19               Bermuda     -17261.101148
94            Luxembourg     -18911.387904

In [114]:
# En yüksek 4 ve en düşük 4 kalkınma endeksine sahip ülkeler
top_4_countries = country_avg_index.head(4)['Ulke']
bottom_4_countries = country_avg_index.tail(4)['Ulke']

# Bu ülkelerin veri setlerini almak
top_4_df = df[df['Ulke'].isin(top_4_countries)]
bottom_4_df = df[df['Ulke'].isin(bottom_4_countries)]

# Toplam veri seti
combined_df = pd.concat([top_4_df, bottom_4_df])

In [115]:
combined_df

,Ulke,Yil,Elektrik_Erisim_%,Temiz_Yakit_Erisim,Yenilenebilir_Kapasite_KisiBasi,Gelismis_Ulkeler_Finansal_Akisi,Yenilenebilir_Enerji_Orani,Fosil_Yakit_Elektrik_TWh,Nukleer_Elektrik_TWh,Yenilenebilir_Elektrik_TWh,...,Enerji_Yoğunluğu,CO2_Emisyonu_kt,Yenilenebilir_Enerji_%,Gdp_Buyume,Gdp_KisiBasi,Nufus_Yogunlugu,Yuzolcumu_Km2,Enlem,Boylam,Kalkinma_Endeksi
714,China,2000,97.021800,42.0,58.780000,243620000.0,29.63,1113.30,16.74,225.56,...,10.85,3.346530e+06,5.656925,8.490093,959.372484,153.0,9596960.0,35.861660,104.195397,167214.987719
715,China,2001,97.272790,42.3,61.010000,325050000.0,28.36,1182.59,17.47,280.73,...,10.36,3.529080e+06,6.618624,8.335733,1053.108243,153.0,9596960.0,35.861660,104.195397,176330.514073
716,China,2002,97.516205,43.1,63.680000,218270000.0,27.00,1337.46,25.13,291.41,...,10.12,3.810060e+06,6.280488,9.133631,1148.508290,153.0,9596960.0,35.861660,104.195397,190375.516817
717,China,2003,97.754380,43.4,70.240000,22510000.0,23.86,1579.96,43.34,287.28,...,10.48,4.415910e+06,5.301109,10.038030,1288.643252,153.0,9596960.0,35.861660,104.195397,220663.686288
718,China,2004,97.989670,44.9,77.850000,32680000.0,20.17,1795.41,50.47,357.43,...,10.83,5.124820e+06,5.600940,10.113621,1508.668098,153.0,9596960.0,35.861660,104.195397,256086.046087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3223,Switzerland,2015,100.000000,100.0,113.137498,94224000.0,23.94,3.33,22.09,36.73,...,1.80,3.909000e+04,33.162600,1.657769,84776.142170,219.0,41277.0,46.818188,8.227512,-15044.351842
3224,Switzerland,2016,100.000000,100.0,113.137498,94224000.0,24.10,3.69,20.24,33.57,...,1.72,3.967000e+04,32.287403,2.045186,83073.280080,219.0,41277.0,46.818188,8.227512,-14674.817635
3225,Switzerland,2017,100.000000,100.0,113.137498,94224000.0,24.99,3.67,19.50,33.45,...,1.70,3.870000e+04,32.014774,1.584820,83352.088650,219.0,41277.0,46.818188,8.227512,-14779.101165
3226,Switzerland,2018,100.000000,100.0,113.137498,94224000.0,24.20,3.54,24.41,34.32,...,1.66,3.748000e+04,31.950867,2.916905,86388.404950,219.0,41277.0,46.818188,8.227512,-15447.498299
3227,Switzerland,2019,100.000000,100.0,113.137498,94224000.0,24.76,3.58,25.28,37.64,...,1.68,3.738000e+04,33.137398,1.210992,85334.519460,219.0,41277.0,46.818188,8.227512,-15241.517237