In [9]:
import numpy as np 
import pandas as pd 

import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
import warnings
import pycountry_convert as pc
from sklearn.linear_model import LinearRegression


warnings.filterwarnings("ignore", category=FutureWarning, module="plotly")
pio.renderers.default='notebook'

In [10]:
df = pd.read_csv('global_data.csv')

In [11]:
display(df)

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3649 entries, 0 to 3648
Data columns (total 21 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3649 non-null   object
 1   Year                                                              3649 non-null   int64
 2   Access to electricity (% of population)                           3639 non-null   float64
 3   Access to clean fuels for cooking                                 3480 non-null   float64
 4   Renewable-electricity-generating-capacity-per-capita              2718 non-null   float64
 5   Financial flows to developing countries (US $)                    1560 non-null   float64
 6   Renewable energy share in the total final energy consumption (%)  3455 non-null   float64
 7   Electricity from fossil fuels (TWh)                               3628 non-null   float64
 8   Electricity from nuclear (TWh)                                    3523 non-null   float64
 9   Electricity from renewables (TWh)                                 3628 non-null   float64
 10  Low-carbon electricity (% electricity)                            3607 non-null   float64
 11  Primary energy consumption per capita (kWh/person)                3649 non-null   float64
 12  Energy intensity level of primary energy (MJ/$2017 PPP GDP)       3442 non-null   float64
 13  Value_co2_emissions_kt_by_country                                 3221 non-null   float64
 14  Renewables (% equivalent primary energy)                          1512 non-null   float64
 15  gdp_growth                                                        3332 non-null   float64
 16  gdp_per_capita                                                    3367 non-null   float64
 17  Density\n(P/Km2)                                                  3648 non-null   object
 18  Land Area(Km2)                                                    3648 non-null   float64
 19  Latitude                                                          3648 non-null   float64
 20  Longitude                                                         3648 non-null   float64
dtypes: float64(18), int64(1), object(2)
memory usage: 598.8+ KB

In [14]:
# Mevcut sütun isimlerini yeni isimlerle değiştirme
df.columns = [
    "Ulke",  # Entity
    "Yil",  # Year
    "Elektrik_Erisim_%",  # Access to electricity (% of population)
    "Temiz_Yakit_Erisim",  # Access to clean fuels for cooking
    "Yenilenebilir_Kapasite_KisiBasi",  # Renewable-electricity-generating-capacity-per-capita
    "Gelismis_Ulkeler_Finansal_Akisi",  # Financial flows to developing countries (US $)
    "Yenilenebilir_Enerji_Orani",  # Renewable energy share in the total final energy consumption (%)
    "Fosil_Yakit_Elektrik_TWh",  # Electricity from fossil fuels (TWh)
    "Nukleer_Elektrik_TWh",  # Electricity from nuclear (TWh)
    "Yenilenebilir_Elektrik_TWh",  # Electricity from renewables (TWh)
    "Dusuk_Karbon_Elektrik_%",  # Low-carbon electricity (% electricity)
    "KisiBasi_Enerji_Tuketimi",  # Primary energy consumption per capita (kWh/person)
    "Enerji_Yoğunluğu",  # Energy intensity level of primary energy (MJ/$2017 PPP GDP)
    "CO2_Emisyonu_kt",  # Value_co2_emissions_kt_by_country
    "Yenilenebilir_Enerji_%",  # Renewables (% equivalent primary energy)
    "Gdp_Buyume",  # gdp_growth
    "Gdp_KisiBasi",  # gdp_per_capita
    "Nufus_Yogunlugu",  # Density\n(P/Km2)
    "Yuzolcumu_Km2",  # Land Area(Km2)
    "Enlem",  # Latitude
    "Boylam"  # Longitude
]

# Yeni sütun isimlerini kontrol edelim
df

,Ulke,Yil,Elektrik_Erisim_%,Temiz_Yakit_Erisim,Yenilenebilir_Kapasite_KisiBasi,Gelismis_Ulkeler_Finansal_Akisi,Yenilenebilir_Enerji_Orani,Fosil_Yakit_Elektrik_TWh,Nukleer_Elektrik_TWh,Yenilenebilir_Elektrik_TWh,...,KisiBasi_Enerji_Tuketimi,Enerji_Yoğunluğu,CO2_Emisyonu_kt,Yenilenebilir_Enerji_%,Gdp_Buyume,Gdp_KisiBasi,Nufus_Yogunlugu,Yuzolcumu_Km2,Enlem,Boylam
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

### Normalizasyon işlemleri

In [15]:
from sklearn.preprocessing import StandardScaler

# İlgili sütunları seçelim
columns_to_use = [
    'Elektrik_Erisim_%', 'Temiz_Yakit_Erisim', 
    'Yenilenebilir_Kapasite_KisiBasi', 'Yenilenebilir_Enerji_Orani',
    'KisiBasi_Enerji_Tuketimi', 'Enerji_Yoğunluğu',
    'Gdp_KisiBasi', 'Nufus_Yogunlugu'
]
data = df[columns_to_use].copy()

# Eksik değerleri sütun ortalamaları ile doldurmak (ya da başka bir impute yöntemi)
data.fillna(data.mean(), inplace=True)

# Normalizasyon
scaler = StandardScaler()
data_normalized = scaler.fit_transform(data)

TypeError: can only concatenate str (not "int") to str